### PR TITLE
New logos

### PR DESCRIPTION
**Pull request by loriab**
## Description
hybridized the Psi4 and NumPy logos to make a distinctive set

## What are your new additions? Please provide a brief list.
* **New Features**
  - [x] Usual banner and square forms
  - [x] README with color/font guidance

## Status
- [x] Click when ready for review-and-merge

### CODE REVIEW

**Comment by dgasmith** [comment]
I like it, do we know if there is any copyright concerns with using NumPy's logo in this fashion?

**Comment by dsirianni** [comment]
I can't find anything regarding a copyright or trademark of the NumPy logo itself; therefore, I would assume it also falls under the BSD-3c license and is able to be modified and redistributed.  I suppose that to be extra safe we could contact them to obtain express written approval for our adaptation.

**Comment by dgasmith** [comment]
Best to be safe, ill shoot them an email. BSD-3C doesn't cover non-code well, you really need a CC license for that.

**Comment by loriab** [comment]
It's independently constructed, different dimensions, different colors. And we're using NumPy as-is, so there's no sly appropriation. I think it's safe, but could contact NumFOCUS, as NumPy's legal guardians, if you want to check.

**Comment by dgasmith** [comment]
We do need to ask the NumPy mailing list about this, initial impressions is that this is fine however.

**Comment by loriab** [comment]
done!

**Pull request merged**
