### PR TITLE
Correction to QED-CIS

### PR DESCRIPTION
**Pull request by BauerMarco**
## Description
The additional diagonal contributions to the bilinear coupling in QED-CIS should cancel. This is also wrong in the publication, which has already been discussed with the author and will hopefully be taken care of soon.

## What are your new additions? Please provide a brief list.
* **New Features**
  - [ ] QED-CIS is correct now

* **Changes**
  - [ ] Deleted terms, which should cancel anyway, but leave a nuclear dipole contribution in the previous implementation.
  - [ ] Corrected corresponding test 

## Status
- [x] Click when ready for review-and-merge

### CODE REVIEW

**Comment by JonathonMisiewicz** [comment]
Can @FoleyLab confirm?

**Comment by FoleyLab** [comment]
> 

@JonathonMisiewicz Yes I discussed this issue with Marco offline some time ago.  I will review this PR and the corrections this week and comment here!

**Review by FoleyLab — APPROVED** [review]
@BauerMarco this looks good and I have an independent implementation that agrees with the new values in CS_CQED_CIS.py. One minor suggested edit: on line 225 of helper_CS_CQED_CIS.py change  remove the "off-diagonals first" from the comment # bilinear coupling - off-diagonals first (i.e. just # bilinear coupling).

**Comment by JonathonMisiewicz** [comment]
Great, thanks! I am going to request an update to the citation when the erratum/follow-up comes out, but otherwise, LGTM.

**Review by JonathonMisiewicz — APPROVED** [review]

**Pull request merged**
