### PR TITLE
LCCD

### PR DESCRIPTION
**Pull request by JonathonMisiewicz**
## Description
Add spinorbital LCCD to Psi4Numpy so @loriab has a nice reference implementation when standardizing CEPA tests.

## What are your new additions? Please provide a brief list.
* **New Features**
  - [x] LCCD code

## Status
- [x] Click when ready for review-and-merge

### CODE REVIEW

**Comment by loriab** [comment]
* don't worry about the RHF_symmetry fail -- I've fixed that in a local psi.
* but since you made a new folder for cepa, do please create a file analogous to https://github.com/psi4/psi4numpy/blob/master/tests/test_RI_CC.py with a 3-line section to trigger your script to run.

**Comment by JonathonMisiewicz** [comment]
I'm seeing a test failure due to `CURRENT CORRELATION ENERGY` not being available out of `fnocc`'s wavefunction. Let me guess: that change was more recent than the version of Psi that P4N Travis uses?

**Comment by loriab** [comment]
Yes, filling in of fnocc vars happened with https://github.com/psi4/psi4/pull/1850 . I did get a clean test suite locally on the reference implementation side last night after

```
diff --git a/psi4/src/export_mints.cc b/psi4/src/export_mints.cc
index 1af1647..9e08a59 100644
--- a/psi4/src/export_mints.cc
+++ b/psi4/src/export_mints.cc
@@ -964,10 +964,10 @@ void export_mints(py::module& m) {
         // One-electron
         .def("ao_overlap", oneelectron(&MintsHelper::ao_overlap), "AO basis overlap integrals")
         .def("ao_overlap", oneelectron_mixed_basis(&MintsHelper::ao_overlap), "AO mixed basis overlap integrals")
-        .def("so_overlap", &MintsHelper::so_overlap, "SO basis overlap integrals")
+        .def("so_overlap", &MintsHelper::so_overlap, "SO basis overlap integrals", "include_perturbations"_a = true)
         .def("ao_kinetic", oneelectron(&MintsHelper::ao_kinetic), "AO basis kinetic integrals")
         .def("ao_kinetic", oneelectron_mixed_basis(&MintsHelper::ao_kinetic), "AO mixed basis kinetic integrals")
-        .def("so_kinetic", &MintsHelper::so_kinetic, "SO basis kinetic integrals")
+        .def("so_kinetic", &MintsHelper::so_kinetic, "SO basis kinetic integrals", "include_perturbations"_a = true)
         .def("ao_potential", oneelectron(&MintsHelper::ao_potential), "AO potential integrals")
         .def("ao_potential", oneelectron_mixed_basis(&MintsHelper::ao_potential), "AO mixed basis potential integrals")
         .def("so_potential", &MintsHelper::so_potential, "SO basis potential integrals",
```

**Comment by JonathonMisiewicz** [comment]
Should I change this to use something friendlier to older Psi, or is it fine as-is?

Once this is merged in, I can start on LCCSD.

**Pull request merged**
