### PR TITLE
remove xfail after psi update

### PR DESCRIPTION
**Pull request by loriab**
## Status
- [ ] Click when ready for review-and-merge

### CODE REVIEW

**Comment by JonathonMisiewicz** [comment]
Test failure is the result of a genuine bug in my code. You need the `integrals.py` changes to #99 to get this working. I can make a separate PR out of that if needed.

**Comment by loriab** [comment]
yeah, I was just trying to figure out that past and future of integrals, integrals_DF, and OEI. easiest I think just to bring in #99, then this one. I have added the fnocc cepa conv-only warning in in my local psi.

**Comment by loriab** [comment]
first travis-ci lane is psi4 v1.3.2, so the wfn `CURRENT CORRELATION ENERGY` won't ever be fixed there. I'll switch the conv ref impl to globals for compatibility.

**Comment by JonathonMisiewicz** [comment]
Sad, but I can live with it.

**Pull request merged**
