### PR TITLE
Update to new `set_memory()` API

### PR DESCRIPTION
**Pull request by dsirianni**
**Accomplished:**
- [x] Updated all memory setting in reference implementations to new `psi4.set_memory()` API
- [x] Fixed `scf_helper` init bug in `ROHF_libJK.py`
- [x] Updated printing in `MPn.py`

**User Changes:**
- [x] New string arguments to `psi4.set_memory()` available to users.

**Status:**
- [x] Ready

### CODE REVIEW

**Comment by dgasmith** [comment]
I probably wont pull this in for awhile yet as this change means that everyone has to have an absolutely up to date psi4.

**Comment by dsirianni** [comment]
Sure thing. Maybe once the 1.1 release gets nailed down.

**Comment by dsirianni** [comment]
We could probably safely pull this in now, since 1.1 is required.

**Comment by dgasmith** [comment]
Agreed.

**Pull request merged**
