### PR TITLE
Add Grid Tutorial

### PR DESCRIPTION
**Pull request by VHchavez**
## Description
Addition of a tutorial that exemplifies how to calculate quantities, specifically the molecular orbitals, on a grid different than the DFT grid. Useful for people who want to visualize quantities without needing a cube file. 
The tutorial ended up covering some material already in the current 4a. My guess is that this tutorial could replace the current 4a. 

I spoke with @dgasmith, and he mentioned the possibility of moving the subject into its own folder. This could be a great idea If additional grid tutorials (@hokru 👀) are added. I hope you can help take a look as well, @hokru.
Hopefully, there are not too many Psi4 malpractices in it 😅. Thanks! 

## Status
- [x] Click when ready for review-and-merge

### CODE REVIEW

**Comment by dgasmith** [comment]
I think you accidentally removed the old tutorial and replaced with it with your new one? Having the be 4a/4b I think makes sense for now.

**Comment by dgasmith** [comment]
Reading through your comment I think they should approach different topics? 4a was a "compute the DFT energy" while 4b is more "cast arbitrary orbital-like matrices to a grid". It has been awhile since I have seen this folder so go easy on me.

**Comment by VHchavez** [comment]
> Reading through your comment I think they should approach different topics? 4a was a "compute the DFT energy" while 4b is more "cast arbitrary orbital-like matrices to a grid". It has been awhile since I have seen this folder so go easy on me.

No problem! 
4a_DFT_Grids plots how the DFT grid looks, whereas the 4b does talk about "cast arbitrary orbital-like matrices to a grid" but is specifically oriented to computing the exchange-correlation energy. 
The tutorial does show what was already in 4a_DFT_Grids.  It also focuses on generating the blocks of points from scratch, and it uses them to visualize the orbitals. I guess that it can be seen as the combination of 4a and 4b. 

I initially had this new tutorial as 4f until I noticed the similarities with 4a.

**Review by dgasmith — APPROVED** [review]
LGTM if you think this is ready to go!

**Comment by VHchavez** [comment]
I think it's ready. 
Do we need another reviewer to approve it?

**Comment by VHchavez** [comment]
Hello Daniel 🐶! Just wondering if there's anything else we want to add/fix before merging?

**Comment by dgasmith** [comment]
Let's do it! This looks amazing- thanks!

**Pull request merged**
