### PR TITLE
heal CI, take 2

### PR DESCRIPTION
**Pull request by loriab**
* **Changes**
  - [x] don't pin to ancient numpy  

## Status
- [ ] Click when ready for review-and-merge

### CODE REVIEW

**Comment by dgasmith** [comment]
Looks like 3.6 upstream has not yet built? 3.7 passed with flying colors.

**Comment by loriab** [comment]
the py36 lane is attached to psi4 release, so it's failing b/c `CPHF_TASKS` not in v1.3. so that one won't pass until v1.3.1

the py37 lane is attached to nightly build, so it's ok. (I need to add pylibefp so no skips.)

**Comment by dgasmith** [comment]
Ok, do you want to go ahed and merge?

**Comment by loriab** [comment]
I was going to wait until full green, but it's fine to merge.

**Pull request merged**
