### PR TITLE
RESP and py27

### PR DESCRIPTION
**Pull request by loriab**
## Description
Aha! Once again, I'm not crazy — the code is. This PR checks RESP better and shows that 27 is a problem. Issue has to to with options processing and resp_a not getting reset to 0.001 in stage2. Looking into it, but at least I know I didn't break it. @alenaizan 

## Status
- [x] Click when ready for review-and-merge

### CODE REVIEW

**Comment by loriab** [comment]
Ok, this fixes the immediate problem. I suspect it was developed with py36, where dicts are inherently ordered? The `sorted` incorporates the assumption that lowercase `resp_a` trumps `RESP_A`. If instead you're relying on last-in trumps earlier-in, we'll have to revisit.

**Comment by dgasmith** [comment]
Well, dropping Py27 support soon. Wouldn't worry about it, is this ready?

**Comment by loriab** [comment]
For the psi4 plugin, I'll need Asim to answer the question about did I correct it with the right assumption. But current state of this PR is better than `master` so, sure, RTG. Can always do a follow-up PR.

**Comment by alenaizan** [comment]
Good catch @loriab . Never though about it. Is there a better way to guard against this kind of error?

**Comment by loriab** [comment]
Not that I know if besides always using OrderedDict if you’re going to depend on that behavior. Python used to expose your error pretty quickly but no more.

**Pull request merged**
