### PR TITLE
Pytest

### PR DESCRIPTION
**Pull request by loriab**
## Description
Uses pytest instead of hand-written script (not yet deleted), filters tests depending on if dependent software available, sets up a minimal 27 and maximal 36 travis matrix, fixes up the magics.

## Any questions for the community?
- [x] @dgasmith, as mentioned (and viewable https://travis-ci.org/loriab/psi4numpy/jobs/276189979), getting an indexing error on 4e?

## Status
- [x] Ready for review. SQUASH

### CODE REVIEW

**Comment by dgasmith** [comment]
Cool, I like it. I just fixed up 4e. So pull that in and rebase this when you get a chance. We should be good to go.

**Comment by loriab** [comment]
Ok, this is all working now. Last commit is just removing former testing script and adding codecov badge. Ready for review and merge.

Note that weakness I forgot to mention is that pytest only works from w/i `tests/` dir. It's a matter of needing a fixed location to find files wrt. Ordinarily a module import would do the job, but no such here. So, a weakness, but not a fatal one, imo.

**Comment by dgasmith** [comment]
I usually fix that with a `base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))` in something like the `utils.py`.

**Comment by loriab** [comment]
works great, @dgasmith, thanks!

**Comment by loriab** [comment]
passing and RTG. and again, SQUASH

**Pull request merged**
