### PR TITLE
Add Ewald and PME tutorial

### PR DESCRIPTION
**Pull request by andysim**
## Description
A tutorial detailing the derivation of classical electrostatics and Ewald summation.

## What are your new additions? Please provide a brief list.
* **New Features**
  - [x] Ewald and PME tutorial, with complete derivation.

## Any questions for the community?
- [ ] Where does this belong in the folder structure, and which .md files need to reference it?
- [ ] Does this even belong in this notebook collection? It's far more derivation-heavy than the contribution guidelines request, so feel free to reject this PR.

## Status
- [ ] Click when ready for review-and-merge

### CODE REVIEW

**Comment by loriab** [comment]
Looks like a great notebook to me. Thanks, @andysim.

When I run it, get this. Ring any bells?
```
Traceback (most recent call last):
  File "/tmp/tmpm1ryen23/12a_ewald.py", line 644, in <module>
    Uvals = np.array([efunc(*p) for p in params])
  File "/tmp/tmpm1ryen23/12a_ewald.py", line 644, in <listcomp>
    Uvals = np.array([efunc(*p) for p in params])
  File "/tmp/tmpm1ryen23/12a_ewald.py", line 637, in PME_energy
    Urec = PME_rec_energy(alpha, maxm, splineorder)
  File "/tmp/tmpm1ryen23/12a_ewald.py", line 580, in PME_rec_energy
    gridstart[atom,:] = map(int, mdim*coord-1e-8)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'map'
```

**Comment by andysim** [comment]
Oops, my jupyter setup is configured for 2.7.  Let me run it in 3 and push a fix.  Thanks for the heads-up.

**Comment by loriab** [comment]
np, we test in 2.7 and a 3.6 just to catch stuff like this. I'll PR to your PR with the testing set up after your fix. thanks.

**Comment by dgasmith** [comment]
Super awesome, thanks Any!

PS: I keep trying to kill Codecov-bot, but it won't die.

**Comment by andysim** [comment]
Should be fixed now.  I had a rogue miniconda2 that sneaked into my environment somehow.  Didn't know before, but `map(int, [0.1, 0.2])` returns a map object in py3, not a list of ints.

**Comment by dgasmith** [comment]
Python3: Anything that can return an iterator will. Try `list( map(int, [0.1, 0.2]))`.

**Comment by andysim** [comment]
Thanks for the info; your suggestion is what I did in the last commit.  Seems to be working now.

**Comment by andysim** [comment]
Thanks for the testing setup, @loriab; I just saw the guidelines in contributing.md that I somehow overlooked before.  Absolute values are a little tricky to test in this case, because the random number generator is used to build coordinates.  I can do value comparisons of the energies of different alpha values at the end, however.

**Comment by dsirianni** [comment]
This definitely belongs here -- the point of including derivations within tutorial notebooks is to bring the reader up-to-speed enough with the underlying theory to grasp the intricacies of the code, which I think this tutorial does very nicely.  

I dunno about anyone else, but I think this should be in its own subdirectory within the `Tutorials/` folder, like `12_Classical-Mechanics` and perhaps even a subdirectory within that, if we ever add more MD/MC/etc. tutorials.    Thoughts, @dgasmith & @loriab? 

In any event, the main `Tutorials/README.md` could use an update...I'll work on that now.

**Comment by loriab** [comment]
np, that was a fairly recent addition. Basically, any test you can add that provides moderate assurance that upon software update the notebook is generating steady values and not jibberish will be helpful.

Go ahead and add `@using_scipy` [here](https://github.com/andysim/psi4numpy/blob/ewald/tests/test_TU_12.py#L8) (in addition to `@using_matplotlib`). And please add `scipy` to [this line](https://github.com/andysim/psi4numpy/blob/master/.travis.yml#L33) as I think it's more important to test all contributions for py27 than to catch test that need scipy.

**Comment by andysim** [comment]
I think that a more general subdirectory is a great idea, @dsirianni.  I have another tutorial that needs a lot of polishing, but introduces some basics like Verlet integration (already covered elsewhere in psi4numpy) and cutoff methods to conserve energy.  Perhaps if I clean that up, and move it to 12a, with Ewald being 12b, subdirectory 12 can serve as a basic intro to MD for us QM folks?

**Comment by loriab** [comment]
@dsirianni, this _is_ in its own dir w/i the Tutorials/ folder? I'm not keen on further subfoldering – would need to adjust the tests structure. In fact, in the absence of some nice Dewey Decimal System for quantum chemistry, I was wondering if we wanted to (aside from chapter 0. Intro) just register all notebooks by number in order or receipt so they had a firm identity outside of folder organization.

**Comment by dgasmith** [comment]
@andysim Can you use `np.random.seed(0)`?

I wouldn't mind a `QM_Tutorials/MD_Tutorials` folder?

**Comment by loriab** [comment]
To be clear, I'm perfectly happy with ~`Tutorials/12_MD/[058|12a|12b]ewald.ipynb`. I'd just rather not see `Tutorials/12_MD/ClassicalElst/Ewald.ipynb`, at least not unless p4n swells by an order of magnitude. (Speaking as one who lost a tutorial for a while in the existing dir structure.)

**Comment by loriab** [comment]
I had to look, but it seems p4n doesn't regularly do `ValidationError`s. Probably plain `print` and `sys.exit(1)` instead.

**Comment by dgasmith** [comment]
I think everything is ready, any remaining issues?

**Comment by dgasmith** [comment]
Thanks Andy! This is really awesome stuff. Lets get this in now and I might have a few more comments during a cleanup pass in a bit.

**Pull request merged**
